### PR TITLE
First draft of IPFS Weekly #51

### PR DESCRIPTION
**Pull request by jennwrites**
Looking for feedback and suggestions on this draft so that we can send it out via TinyLetter (and post on the blog) Tuesday, July 23. 🏄‍♀️

Thanks!

### CODE REVIEW

**Comment by momack2** [comment]
### New IPFS Documentation Role
Title: Documentation & Technical Content Strategist, IPFS
Company: Protocol Labs
Location: Anywhere on the internet
Link: https://jobs.lever.co/protocol/e7db2c84-afd7-44a4-9a27-449c751d8289

(note, **only** include if there is >1 institution looking for IPFS-skilled humans represented in this jobs section)

**Comment by momack2** [comment]
### Existing IPFS Tech Lead role
Title: Distributed Systems Technical Lead, IPFS
Company: Protocol Labs
Location: Anywhere on the internet
Link: https://jobs.lever.co/protocol/9283f9b0-de64-4e1f-a221-5d02b0202198

**Comment by jennwrites** [comment]
Will include job listing in next week’s edition, had to lock down a finalized version for translation before it was submitted.

**Comment by jennwrites** [comment]
IPFS Weekly #51 was published

-On the [IPFS blog](still pending)
-To 2871 subscribers [via Tinyletter](https://tinyletter.com/ipfsnewsletter/letters/ipfs-weekly-51)

**Pull request merged**
