### PR TITLE
Version 0.1 of a tool to get a list of commit authors for the previous week

### PR DESCRIPTION
**Pull request by eminence**
See #1

### CODE REVIEW

**Comment by eminence** [comment]
Example output, getting all the commits for the 7-day period before Monday:

```
$ venv/bin/python tools/get_commits.py --end "Jan 4th" --days=7 $HOME/ipfs_stuff/repos/

Getting all commits made between Mon Jan  4 00:00:00 2016 and Mon Dec 28 00:00:00 2015
Scanning for repos... Found 67 repos
If they have a remote named `origin`, it will be fetched from...
Fetch complete for git://github.com/ipfs/js-ipfs-path
Fetch complete for git://github.com/ipfs/install-go-ipfs
Fetch complete for git://github.com/ipfs/go-commands
Fetch complete for git://github.com/ipfs/faq
Fetch complete for git://github.com/ipfs/archives
Fetch complete for git://github.com/ipfs/distributions
Fetch complete for git://github.com/ipfs/go-ipfs-api
Fetch complete for git://github.com/ipfs/swift-ipfs-api
Fetch complete for git://github.com/ipfs/java-ipfs-api
Fetch complete for git://github.com/ipfs/papers
Fetch complete for git://github.com/ipfs/js-ipfs
Fetch complete for git://github.com/ipfs/website
Fetch complete for git://github.com/ipfs/logo
Fetch complete for git://github.com/ipfs/blog
Fetch complete for git://github.com/ipfs/fs-repo-migrations
Fetch complete for git://github.com/ipfs/js-ipfs-repo
Fetch complete for git://github.com/ipfs/station
Fetch complete for git://github.com/ipfs/ipfs.js
Fetch complete for git://github.com/ipfs/refs-denylists-dmca
Fetch complete for git://github.com/ipfs/dir-index-html
Fetch complete for git://github.com/ipfs/dataviz
Fetch complete for git://github.com/ipfs/apps
Fetch complete for git://github.com/ipfs/api
Fetch complete for git://github.com/ipfs/go-log
Fetch complete for git://github.com/ipfs/file-browser
Fetch complete for git://github.com/ipfs/refs
Fetch complete for git://github.com/ipfs/community
Fetch complete for git://github.com/ipfs/go-libp2p
Fetch complete for git://github.com/ipfs/go-ipfs
Fetch complete for git://github.com/ipfs/ipfs-npm
Fetch complete for git://github.com/ipfs/ipfs-hubot
Fetch complete for git://github.com/ipfs/refs-solarnet-storage
Fetch complete for git://github.com/ipfs/go-blocks
Fetch complete for git://github.com/ipfs/py-ipfs
Fetch complete for git://github.com/ipfs/notes
Fetch complete for git://github.com/ipfs/container-demos
Fetch complete for git://github.com/ipfs/go-ipld
Fetch complete for git://github.com/ipfs/starlog
Fetch complete for git://github.com/ipfs/ipfs-web-app
Fetch complete for git://github.com/ipfs/go-iprs
Fetch complete for git://github.com/ipfs/dnslink-deploy
Fetch complete for git://github.com/ipfs/infrastructure
Fetch complete for git://github.com/ipfs/go-ipfs-util
Fetch complete for git://github.com/ipfs/ipfs-readme-standard
Fetch complete for git://github.com/ipfs/examples
Fetch complete for git://github.com/ipfs/scala-ipfs-api
Fetch complete for git://github.com/ipfs/ipfs-js-defaults
Fetch complete for git://github.com/ipfs/specs
Fetch complete for git://github.com/ipfs/ops-requests
Fetch complete for git://github.com/ipfs/bitswap-ml
Fetch complete for git://github.com/ipfs/archive-format
Fetch complete for git://github.com/ipfs/ipfs-update
Fetch complete for git://github.com/ipfs/js-ipfs-api
Fetch complete for git://github.com/ipfs/POST
Fetch complete for git://github.com/ipfs/python-ipfs-api
Fetch complete for git://github.com/ipfs/ipfs-geoip
Fetch complete for git://github.com/ipfs/pm
Fetch complete for git://github.com/ipfs/project-repos
Fetch complete for git://github.com/ipfs/fs-stress-test
Fetch complete for git://github.com/ipfs/npm-go-ipfs
Error while fetching for /storage/home/achin/ipfs_stuff/repos/weekly/.git git@github.com:eminence/weekly.git
Fetch complete for git://github.com/ipfs/blockchain-data
Fetch complete for git://github.com/ipfs/awesome-ipfs
Fetch complete for git://github.com/ipfs/webui
Fetch complete for git://github.com/ipfs/ipfs-blob-store
Fetch complete for git://github.com/ipfs/ipfs
Fetch complete for git://github.com/ipfs/support

Contributors for this period (Mon Dec 28 00:00:00 2015 to Mon Jan  4 00:00:00 2016):
* Adam Gashlin
* Christian Couder
* David Dias
* Friedel Ziegelmayer
* Harlan T Wood
* Ian Preston
* Jakub (Kubuxu) Sztandera
* Jeromy Johnson
* Lars Gierth
* ReadmeCritic
* Richard Littauer
* Travis Person
* dignifiedquire
* greenkeeperio-bot
* rht

```

**Comment by RichardLitt** [comment]
Looks like this works pretty well!

**Comment by RichardLitt** [comment]
What about looking through the events stream? https://developer.github.com/v3/activity/events/#list-public-events-for-an-organization

**Comment by jbenet** [comment]
i think this lgtm

**Comment by jbenet** [comment]
(good stuff!)

**Comment by RichardLitt** [comment]
Thanks, @eminence!

**Comment by eminence** [comment]
(I replied in IRC, but I forgot to reply here for all to see)

I believe that using the event stream will actually be the best way forward, even for getting a list of commits.  For two reasons:
- It'll allow us to get a list of github comments
- It'll allow us to map commits to github usernames (which is really hard to do right now)

**Comment by RichardLitt** [comment]
I agree. So, let's go with that. I'll build a prototype, unless you want to go with python. Doesn't bother me.

**Comment by RichardLitt** [comment]
@eminence Damn. The event stream tops out at 300. So, we can't use that, as IPFS will have more than that many events in a given week. We're going to have do continue doing what we've been doing.

**Comment by RichardLitt** [comment]
Nevermind, working on it.

**Pull request merged**
