### PR TITLE
Weekly #7: February 16-22

### PR DESCRIPTION
**Pull request by RichardLitt**
:palm_tree:

### CODE REVIEW

**Comment by hackergrrl** [comment]
Nothing shipped by me last week, but some incremental progress was made:
- :star: Me and @whyrusleeping and @chriscool have been doing lots to make our tests greener. This'll let us get PRs in faster because we won't need to wonder whether our CI is lying to us or not.
- :star: Made progress toward getting `go-ipfs` compatible with vanilla `go get` installation. Hope to have more tangible results to show by end of this week.

**Comment by whyrusleeping** [comment]
as noffle says, we put a lot of effort into making the CI green. This gives us more confidence about the code we ship, and allows us to ship more often.

**Comment by dignifiedquire** [comment]
- [**station**](//github.com/ipfs/station)
  - [@dignifiedquire](//github.com/dignifiedquire) fixed drag and drop
    file uploading, and some dependency issues. So go ahead and try it
    out.
- [**ipfs-geoip**](//github.com/ipfs/ipfs-geoip)
  - [@dignifiedquire](//github.com/dignifiedquire) rewrote the generation
    script and cleaned up the code so that now the data is consistently
    reproducable and fully stored on IPFS. This ensures that geoip lookups
    over IFPS will work in all future releases.

**Comment by chriscool** [comment]
- Made 'ipfs files ls' default to '/'.
- Improved fs-repo-migrations tests by checking that the objects are the same and checking that garbage collection does not change anything.
- Cleaned up sharness tests.

**Comment by RichardLitt** [comment]
- **http-api-spec**: @RichardLitt finished logging all existing `ipfs` commands for the HTTP API Spec. This means that if you have any questions about how the HTTP API should work, you can see them either in master or as open PRs to that issue. One step closer to a fully functional API...
- **community**: @RichardLitt proposed using the new [GitHub Templates]() for IPFS. What do you think about this idea? Chime in [here](https://github.com/ipfs/community/issues/108).
- **community**: We now have [a list of community events](https://github.com/ipfs/community#events-calendar) for IPFS on the ipfs/community README. Do you have any that you'd like to add? Check out past events, too.

**Comment by RichardLitt** [comment]
Thanks. Closing in favor of #17.

**Pull request closed without merging**
