### PR TITLE
First draft of IPFS Weekly 13

### PR DESCRIPTION
**Pull request by jennwrites**
Looking for feedback and suggestions on this draft so that we can send it out via TinyLetter (and post on the blog) Tuesday, October 9.

Thanks!

### CODE REVIEW

**Comment by jamiew** [comment]
Some "new to me" IPFS things I stumbled into this week:

* S3 datastore for IPFS: https://github.com/ipfs/js-datastore-s3/ & https://github.com/ipfs/go-ds-s3 – look like they're coming back to life
* Lidel mentioned it's being used for another very cool work-in-progress, an NPM package mirror powered by IPFS: https://github.com/ipfs-shipyard/npm-on-ipfs

**Comment by jamiew** [comment]
I don't know if they're "official" yet but I've also been keeping some notes on the team's OKRs as they've come together. My highlights

**Comment by jennwrites** [comment]
IPFS Weekly 13 was published:

+ On the IPFS [Weekly Updates issue](https://github.com/ipfs/ipfs/issues/151#issuecomment-428252741)
+ Still pending on IPFS blog
+ And sent to 3099 subscribers [via TinyLetter](https://tinyletter.com/ipfsnewsletter/letters/ipfs-weekly-13)

**Comment by jamiew** [comment]
Motion to close 💯

**Pull request merged**
