### PR TITLE
Weekly #6: February 8th-16th

### PR DESCRIPTION
**Pull request by RichardLitt**
Please add in stuff as you see it!

### CODE REVIEW

**Comment by chriscool** [comment]
I had to send PR #22 as it looks like I don't have the rights to push to this repo.

**Comment by chriscool** [comment]
Feel free to just cherry-pick the commit into this branch.

**Comment by RichardLitt** [comment]
@chriscool that was perfect. As well, you can just comment here in markdown and we'll add it in in the future.

**Comment by RichardLitt** [comment]
Merging with #17.

**Pull request closed without merging**
